### ISSUE TITLE
Error in running the compiler

### ISSUE THREAD

**Issue by godatta** [iic-jku/minimal_ibm_qx_mapping#1]
When I follow the instruction to build the compiler, I am getting errors. Attached is the screenshot showing the error when I run the 'make' command followed by cmake.. There is also the summary of errors in the end..
<img width="1579" alt="Screen Shot 2019-12-02 at 1 21 38 AM" src="https://user-images.githubusercontent.com/46044371/69947371-5d40b280-14a2-11ea-989f-ce258b6a2017.png">
<img width="552" alt="Screen Shot 2019-12-02 at 1 24 39 AM" src="https://user-images.githubusercontent.com/46044371/69947451-85301600-14a2-11ea-8d45-d09745e518a4.png">

**Comment by burgholzer** [comment]
I just pushed an update.
Could you please try to run it now and let us know if it works?

**Comment by godatta** [comment]
The make command works! However, I am running into errors when I am trying to execute the mapping task! I attached the screenshot! Can you please help?
<img width="632" alt="Screen Shot 2019-12-02 at 12 52 19 PM" src="https://user-images.githubusercontent.com/46044371/69994553-f69fb100-1502-11ea-9065-0f487e5c8d53.png">

**Comment by burgholzer** [comment]
I just pushed another commit. There seems to have been an error parsing the input file related to the `isspace(ch)` function in `QASMscanner.cpp`.

Please try and see if it works now!

**Comment by godatta** [comment]
The error is still the same! :(

**Comment by burgholzer** [comment]
There seems to be some kind of problem on your end such that the program can't read the input file properly. I just pushed another small update, which checks if the file was opened correctly.

Could you also try running the program with
`./minimal_mapping *DIR_OF_TEST_FILE*/testExample.qasm`
and see if that works out?

Btw. which compiler are you using?

**Comment by burgholzer** [comment]
@godatta does it work for you now?
