### ISSUE TITLE
More architecture

### ISSUE THREAD

**Issue by qu-tan-um** [iic-jku/minimal_ibm_qx_mapping#2]
I noticed that only ibmqx2/ibmqx4 architecture is included in `main.cpp`. To support an architecture, I think two things are needed: 1) a coupling map, as in all the edges between qubits, and 2) the swap cost of all the possible transitions between any two mappings. 

I think 2) can be derived from 1), but I don't quite get your data structure. For example, you used `stoi` to transform a mapping to a string, but what about when the number of qubits exceeds 11? Then, the mapping can take two digits for a physical qubit.

Can you provide a script that derives 2) from 1)?

**Comment by burgholzer** [comment]
An update for this project is scheduled for late summer 2020. At the moment I cannot promise when exactly that will be. However, if you really want to calculate the swap cost for different architectures right now, you could proceed with an exhaustive breadth-first-search in the following fashion:

Let's assume you want to calculate the minimal SWAP cost for one particular permutation `p`.
Starting with a node representing the identity permutation you apply all SWAPs possible on the architecture (let's say `n`), creating `n` successor nodes with corresponding new permutations and one SWAP. Then you proceed in this fashion breadth-first until you first hit the desired permutation `p`.

I hope this helps. Best regards,
Lukas

**Comment by qu-tan-um** [comment]
Yeah I got the idea, but how is your data structure going to handle more than one digit? For example, right now '2413' stands for the transition 0->0, 1->2, 2->4, 3->1, 4->3. If the qubit count is larger than 10, there are going to be multiple interpretations of the same string '1023...' is it 0->1, 1->0, 2->2, 3->3, ..., or 0->10, 1->2, 2->3?

**Comment by burgholzer** [comment]
The usage of strings in the cost function for IBM QX4 was a choice of convenience, since it works for the 5 qubit architecture.
In general, the cost function takes a permutation vector `std::vector<int>& pi` as input, where `pi[i] = j` means that the permutation maps `i -> j`. (Note that this is _not_ cycle notation as in your post above)
You should be able to apply the bfs-scheme proposed above given this permutation vector, i.e., you can simply write a function 
```c++ 
unsigned int myNewCostFunction(std::vector<int>& pi) {
    unsigned int cost = 0;

    ... bfs search ...

    return cost;
}
```
and then pass it to the mapping routine.

**Comment by qu-tan-um** [comment]
OK. Thanks very much!
